=== bowtie-json-schema/bowtie/bowtie/schemas/models/dialect.json
{
  "description": "Dialect metadata for a dialect of JSON Schema",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$id": "tag:bowtie.report,2024:models:dialect",

  "type": "object",
  "required": ["firstPublicationDate", "prettyName", "shortName", "uri"],
  "properties": {
    "uri": {
      "description": "The URI representing this dialect, also known as its dialect identifier",
      "readOnly": true,

      "type": "string",
      "format": "uri"
    },
    "prettyName": {
      "description": "A human-readable name for the dialect",
      "readOnly": true,

      "type": "string"
    },
    "shortName": {
      "description": "A shorter, slug-like name for the dialect (with no punctuation or spaces) but which still should be unique",
      "readOnly": true,

      "type": "string",
      "pattern": "[a-z]+[a-z0-9-]*"
    },
    "firstPublicationDate": {
      "description": "The date when the dialect was first published publicly as a document",
      "readOnly": true,

      "type": "string",
      "format": "date"
    },
    "hasBooleanSchemas": {
      "description": "Does the dialect have a notion of boolean schemas?",
      "readOnly": true,

      "type": "boolean",
      "default": true
    },
    "aliases": {
      "description": "Other names by which someone may refer to this dialect, officially or otherwise. Such aliases should unambiguously refer to this dialect and no other, so they should be unique not just in the array but also globally, though they may be so short so as to never be used in practice other than when it is clear that dialects are being referred to. For instance simply the number '7' is so short that no one would likely use it in conversation, but would unambiguously refer to the Draft 7 dialect. The dialect's short name is implicitly considered an alias, so it need not appear in this list but should generally be included when using these aliases.",

      "default": [],

      "type": "array",
      "items": { "type": "string" },
      "uniqueItems": true
    }
  },
  "additionalProperties": false
}

=== bowtie-json-schema/bowtie/data/dialects.json
[
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "https://json-schema.org/draft/2020-12/schema",
    "shortName": "draft2020-12",
    "prettyName": "Draft 2020-12",
    "firstPublicationDate": "2020-01-28",
    "aliases": ["2020", "202012", "2020-12", "draft202012"]
  },
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "https://json-schema.org/draft/2019-09/schema",
    "shortName": "draft2019-09",
    "prettyName": "Draft 2019-09",
    "firstPublicationDate": "2019-09-17",
    "aliases": ["2019", "201909", "2019-09", "draft201909"]
  },
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "http://json-schema.org/draft-07/schema#",
    "shortName": "draft7",
    "prettyName": "Draft 7",
    "firstPublicationDate": "2017-11-19",
    "aliases": ["7"]
  },
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "http://json-schema.org/draft-06/schema#",
    "shortName": "draft6",
    "prettyName": "Draft 6",
    "firstPublicationDate": "2017-04-21",
    "aliases": ["6"]
  },
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "http://json-schema.org/draft-04/schema#",
    "shortName": "draft4",
    "prettyName": "Draft 4",
    "firstPublicationDate": "2013-01-31",
    "hasBooleanSchemas": false,
    "aliases": ["4"]
  },
  {
    "$schema": "tag:bowtie.report,2024:models:dialect",
    "uri": "http://json-schema.org/draft-03/schema#",
    "shortName": "draft3",
    "prettyName": "Draft 3",
    "firstPublicationDate": "2010-11-22",
    "hasBooleanSchemas": false,
    "aliases": ["3"]
  }
]
